#!/usr/bin/env python3
"""
Shadow Rail — win-rate / profitability lab (CLI).

Replays the engine's real decision chain over a deterministic candle panel and
prints what each change is worth.  Three modes:

    # 1. headline comparison, in-sample vs out-of-sample
    python3 scripts/backtest.py

    # 2. ablation — one upgrade at a time, so nothing takes credit for another
    python3 scripts/backtest.py --ablate

    # 3. parameter sweep, selected in-sample and validated out-of-sample
    python3 scripts/backtest.py --sweep

The panel is generated by ``app.marketgen`` — the same bar model the simulator
trades — so every configuration is scored on identical, reproducible data.
Absolute numbers describe *that model*, not the live market; what transfers is
the ordering between configurations, and the IS→OOS gap tells you how much of a
result is curve fitting.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "backend"))

from app import backtest as bt                                        # noqa: E402
from app import marketgen                                             # noqa: E402
from app.config import EdgeSettings                                   # noqa: E402
from app.exchange.sim import DEFAULT_UNIVERSE                         # noqa: E402
from app.indicators.ghost import GhostParams                          # noqa: E402

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "data", "backtest")


# --------------------------------------------------------------------------- #
def universe(n: int) -> list[tuple[str, float, float]]:
    seen: set[str] = set()
    rows: list[tuple[str, float, float]] = []
    for sym, price, sigma in DEFAULT_UNIVERSE:
        if sym in seen:
            continue
        seen.add(sym)
        rows.append((sym, price, sigma))
        if len(rows) >= n:
            break
    return rows


def build(bars: int, symbols: int, seed: int):
    t0 = time.time()
    panel = marketgen.generate_panel(universe(symbols), bars, seed=seed)
    t1 = time.time()
    dataset = bt.build_dataset(panel, GhostParams())
    t2 = time.time()
    print(f"panel    : {symbols} symbols × {bars} bars "
          f"({bars * 5 / 60 / 24:.1f} days of 5m candles, seed {seed})")
    print(f"indicator: {sum(len(d.signals) for d in dataset)} candidate flips "
          f"in {t2 - t1:.1f}s (panel {t1 - t0:.1f}s)")
    return panel, dataset


def shipped_config(edge: EdgeSettings | None = None) -> bt.BacktestConfig:
    """The configuration the engine now boots with, expressed for the lab."""
    from app.config import RiskSettings
    risk = RiskSettings()
    return bt.BacktestConfig(
        edge_enabled=True, min_confidence=risk.min_confidence,
        sl_atr_mult=risk.active_tp_sl()[0], tp_enabled=False,
        sizing_mode=risk.sizing_mode, risk_pct_per_trade=risk.risk_pct_per_trade,
        max_margin_per_trade_pct=risk.max_margin_per_trade_pct,
        trail_enabled=risk.trail_roi_enabled, trail_mode=risk.trail_mode,
        trail_activation_r=risk.trail_activation_r,
        trail_distance_r=risk.trail_distance_r,
        trail_min_step_r=risk.trail_min_step_r,
        edge=edge or EdgeSettings())


def row(label: str, res: bt.Result) -> str:
    s = res.summary()
    pf = s["profit_factor"]
    pf_txt = "  ∞ " if pf is None else f"{pf:4.2f}"
    return (f"{label:<26} {s['trades']:>6} {s['win_rate']:>7.1f}% {pf_txt:>6} "
            f"{s['net_pnl']:>10.2f} {s['return_pct']:>8.2f}% "
            f"{s['expectancy_r']:>8.3f}R {s['max_drawdown_pct']:>7.1f}% "
            f"{s['fees']:>9.2f}")


HEADER = (f"{'configuration':<26} {'trades':>6} {'win':>8} {'PF':>6} "
          f"{'net P&L':>10} {'return':>9} {'expect':>9} {'maxDD':>8} {'fees':>10}")


def report(title: str) -> None:
    print()
    print(title)
    print("─" * len(HEADER))
    print(HEADER)
    print("─" * len(HEADER))


# --------------------------------------------------------------------------- #
def compare(dataset, args) -> dict:
    split = int(args.bars * args.split)
    print(f"\nsplit    : in-sample bars 0–{split}, out-of-sample {split}–{args.bars}")

    rows = {}
    configs = {
        "classic (1.5/3.0 ATR, 8% margin)": bt.baseline_config(),
        "shipped edge runner": shipped_config(),
    }
    for name, cfg in configs.items():
        cfg.start_bar, cfg.end_bar = 0, split
        is_res = bt.run_dataset(dataset, cfg, name)
        cfg.start_bar, cfg.end_bar = split, args.bars
        oos_res = bt.run_dataset(dataset, cfg, name)
        rows[name] = {"is": is_res.summary(), "oos": oos_res.summary(),
                      "full": bt.run_dataset(
                          dataset, bt._with_bounds(cfg, 0, args.bars), name).summary()}
        print(f"\n{name}")
        print("  " + HEADER.replace("configuration", "         window"))
        print("  " + row("in-sample", is_res))
        print("  " + row("out-of-sample", oos_res))
    return rows


def ablate(dataset, args) -> dict:
    """Turn one upgrade off at a time (in-sample selection, OOS verification)."""
    split = int(args.bars * args.split)
    variants: list[tuple[str, bt.BacktestConfig]] = []

    def make(**over) -> bt.BacktestConfig:
        """Shipped configuration with a few knobs overridden.

        ``edge_*`` keys go to the edge settings, anything else to the lab config
        (``sl_atr_mult``, ``trail_*`` …).
        """
        base = shipped_config(EdgeSettings(**{k[5:]: v for k, v in over.items()
                                              if k.startswith("edge_")}))
        for key, value in over.items():
            if not key.startswith("edge_"):
                setattr(base, key, value)
        return base

    variants.append(("shipped defaults", make()))
    variants.append(("– entry gates", make(edge_entry_filters_enabled=False)))
    variants.append(("– break-even lock", make(edge_breakeven_enabled=False)))
    variants.append(("– protective trail", make(trail_enabled=False)))
    variants.append(("– drawdown throttle", make(edge_drawdown_throttle_enabled=False)))
    variants.append(("+ confidence sizing", make(edge_confidence_sizing_enabled=True)))
    variants.append(("+ time stop (96 bars)", make(edge_time_stop_enabled=True)))
    variants.append(("+ adaptive vol-normalised stop",
                     make(edge_adaptive_exits_enabled=True)))
    variants.append(("wider stop (10 ATR)", make(sl_atr_mult=10.0)))
    variants.append(("tighter stop (3 ATR)", make(sl_atr_mult=3.0)))
    variants.append(("ROI trail 25/15 pts (max win rate)",
                     make(trail_mode="roi", trail_activation_roi=25.0,
                          trail_distance_roi=15.0)))
    variants.append(("trail 2.5R/1.5R (max expectancy)",
                     make(trail_activation_r=2.5, trail_distance_r=1.5)))

    report("ABLATION — one upgrade switched off at a time "
           "(out-of-sample)")
    out = {}
    for name, cfg in variants:
        is_res = bt.run_dataset(dataset, bt._with_bounds(cfg, 0, split), name)
        oos_res = bt.run_dataset(dataset, bt._with_bounds(cfg, split, args.bars), name)
        out[name] = {"is": is_res.summary(), "oos": oos_res.summary()}
        print(row(name, oos_res))
        print(f"{'':<26} {'in-sample:':>26} {is_res.count:>6} trades, "
              f"win {is_res.win_rate:.1f}%, PF "
              f"{is_res.profit_factor if is_res.profit_factor != float('inf') else 'inf':.2f}, "
              f"net {is_res.net_pnl:+.2f}")
    print("─" * len(HEADER))
    return out


def sweep(dataset, args) -> list:
    split = int(args.bars * args.split)
    cfg = bt.BacktestConfig(edge=EdgeSettings())
    grid = {
        "min_efficiency_ratio": [0.06, 0.10, 0.14],
        "breakeven_arm_r": [0.7, 0.9, 1.1],
        "trail_activation_roi_pct": [15.0, 18.0, 25.0],
        "adaptive_exits_enabled": [True, False],
        "time_stop_bars": [48, 96, 192],
    }
    t0 = time.time()
    rows = bt.sweep(dataset, cfg, grid, split_at=split, min_trades=20)
    report("SWEEP — top 12 by in-sample profit factor; OOS is the honest column")
    for r in rows[:12]:
        p = r["params"]
        tag = ",".join(f"{k}={v}" for k, v in p.items())
        i, o = r["is"], r["oos"]
        print(f"{tag[:60]:<60} IS {i['trades']:>4}t wr {i['win_rate']:>5.1f}% "
              f"PF {i['profit_factor'] or 0:>5.2f} net {i['net_pnl']:>9.2f} | "
              f"OOS {o['trades']:>4}t wr {o['win_rate']:>5.1f}% "
              f"PF {o['profit_factor'] or 0:>5.2f} net {o['net_pnl']:>9.2f}")
    print(f"({len(rows)} configurations, {time.time() - t0:.0f}s)")
    return rows


# --------------------------------------------------------------------------- #
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--bars", type=int, default=12_000, help="bars per symbol (5m)")
    ap.add_argument("--symbols", type=int, default=40)
    ap.add_argument("--seed", type=int, default=20261003)
    ap.add_argument("--split", type=float, default=0.6, help="in-sample fraction")
    ap.add_argument("--ablate", action="store_true")
    ap.add_argument("--sweep", action="store_true")
    ap.add_argument("--save", action="store_true", help="write JSON to data/backtest/")
    args = ap.parse_args()

    panel, dataset = build(args.bars, args.symbols, args.seed)

    payload: dict = {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "seed": args.seed, "bars": args.bars, "symbols": args.symbols,
        "split": args.split,
        "market_model": "marketgen v1 (vol regimes + AR(1) momentum + shocks)",
    }

    report("HEADLINE — baseline vs the upgraded configuration")
    payload["compare"] = compare(dataset, args)

    if args.ablate:
        payload["ablation"] = ablate(dataset, args)
    if args.sweep:
        payload["sweep"] = sweep(dataset, args)

    if args.save:
        os.makedirs(OUT_DIR, exist_ok=True)
        name = f"backtest-{args.seed}-{args.bars}.json"
        with open(os.path.join(OUT_DIR, name), "w") as fh:
            json.dump(payload, fh, indent=2)
        print(f"\nsaved → data/backtest/{name}")
    print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
